import { createContext, useContext, useState, type ReactNode } from "react";

export const LANGUAGES = [
  { code: "en", label: "English", flag: "EN", nativeLabel: "English" },
  { code: "hi", label: "Hindi", flag: "HI", nativeLabel: "हिन्दी" },
  { code: "bn", label: "Bengali", flag: "BN", nativeLabel: "বাংলা" },
  { code: "ta", label: "Tamil", flag: "TA", nativeLabel: "தமிழ்" },
  { code: "te", label: "Telugu", flag: "TE", nativeLabel: "తెలుగు" },
];

export const UI_TEXT: Record<string, Record<string, any>> = {
  en: {
    appName: "Legal AI Assistant",
    appSubtitle: "Ask anything about Indian traffic laws, fines, or rules.",
    newChat: "New Chat",
    noPrevChats: "No previous chats",
    greeting: "How can I help you?",
    greetingSubtitle: "I'm your AI traffic law expert. Ask me about a recent challan, state-specific rules, or fine amounts.",
    placeholder: "Message Pothprohori AI...",
    you: "You",
    aiAssistant: "AI Assistant",
    references: "References:",
    disclaimer: "AI can make mistakes. Always verify legal information with official government sources.",
    responseLanguage: "Response Language",
    suggestions: ["What is the fine for driving without a helmet?", "What are the rules for drunk driving in Delhi?", "Explain Section 177 of the MV Act"],
    navHome: "Home",
    navChat: "Chat",
    navCalc: "Calc",
    navLibrary: "Library",
    signOut: "Sign out",
    welcomeBack: "Welcome back,",
    dailyBriefing: "Your daily traffic law intelligence briefing.",
    startConsultation: "Start Consultation",
    quickActions: "Quick Actions",
    askAI: "Ask AI",
    askAIDesc: "Get legal answers instantly",
    challanCalc: "Challan Calc",
    challanCalcDesc: "Estimate your fine",
    lawLibrary: "Law Library",
    lawLibraryDesc: "Browse 500+ rules",
    lawsIndexed: "Laws Indexed",
    statesCovered: "States Covered",
    aiAccuracy: "AI Accuracy",
    available: "Available",
    featuredLaws: "Featured Laws",
    viewAll: "View all",
    calcTitle: "Challan Calculator",
    calcSubtitle: "Calculate exact traffic fines based on state rules and vehicle type.",
    vehicleType: "Vehicle Type",
    twoWheeler: "Two Wheeler",
    threeWheeler: "Three Wheeler",
    fourWheeler: "Four Wheeler",
    heavyVehicle: "Heavy Vehicle",
    violationType: "Violation Type",
    stateRegion: "State / Region",
    repeatOffense: "Repeat Offense",
    repeatDesc: "Fine is typically doubled for repeat offenders",
    active: "Active",
    calculating: "Calculating...",
    calculateFine: "Calculate Fine",
    challanEstimate: "Challan Estimate",
    violation: "Violation",
    legalSection: "Legal Section",
    region: "Region",
    legalExplanation: "Legal Explanation",
    estimateDisclaimer: "This is an estimate. Actual fine may vary. Consult official sources.",
    poweredBy: "Powered by Gemini AI & RAG Architecture",
    heroTitle1: "Your AI Partner for",
    heroTitle2: "Indian Traffic Laws",
    heroSubtitle: "Instant legal clarity on challans, sections, violations, and state-specific traffic regulations — backed by the Motor Vehicles Act.",
    tryFree: "Try AI Assistant Free",
    challanCalculator: "Challan Calculator",
    comprehensiveTools: "Comprehensive Legal Tools",
    toolsSubtitle: "Everything you need to navigate Indian traffic regulations.",
    aiLegalChat: "AI Legal Chat",
    aiLegalChatDesc: "Ask complex traffic law questions and receive instant, citation-backed answers powered by Gemini AI.",
    startConsult: "Start a consultation",
    calcFine: "Calculate fine",
    browseLibrary: "Browse library",
    lawLibraryTitle: "Law Library",
    lawLibraryLandingDesc: "Browse Motor Vehicles Act, state-level traffic rules, and recent amendments in a structured format.",
    stateIntelligence: "State-Specific Intelligence",
    stateIntelligenceDesc: "Localized traffic law data calibrated for every Indian state.",
    moreStates: "+20 more states",
    ctaTitle: "Ready to understand your traffic rights?",
    ctaSubtitle: "Join thousands of citizens using Pothprohori for instant legal clarity.",
    getStartedFree: "Get Started Free",
    footerDisclaimer: "For educational purposes. Verify with official government sources.",
    signIn: "Sign in",
    getStarted: "Get Started",
    aiAssistantNav: "AI Assistant",
    challanCalcNav: "Challan Calculator",
    lawLibraryNav: "Law Library",
  },
  hi: {
    appName: "कानूनी AI सहायक",
    appSubtitle: "भारतीय यातायात कानून, जुर्माने या नियमों के बारे में कुछ भी पूछें।",
    newChat: "नई चाट",
    noPrevChats: "कोई पिछली चाट नहीं",
    greeting: "मैं आपकी कैसे मदद कर सकता हूं?",
    greetingSubtitle: "मैं आपका AI यातायात कानून विशेषज्ञ हूं। चालान, राज्य-विशिष्ट नियमों या जुर्माने के बारे में पूछें।",
    placeholder: "Pothprohori AI से पूछें...",
    you: "आप",
    aiAssistant: "AI सहायक",
    references: "संदर्भ:",
    disclaimer: "AI गलती कर सकता है। कृपया सरकारी स्रोतों से सत्यापित करें।",
    responseLanguage: "उत्तर की भाषा",
    suggestions: ["बिना हेलमेट के चलाने पर जुर्माना क्या है?", "दिल्ली में नशे में गाड़ी चलाने के नियम क्या हैं?", "MV अधिनियम की धारा 177 समझाएं"],
    navHome: "होम",
    navChat: "चैट",
    navCalc: "कैल्क",
    navLibrary: "लाइब्रेरी",
    signOut: "लॉग आउट",
    welcomeBack: "स्वागत है,",
    dailyBriefing: "आपका दैनिक यातायात कानून ब्रीफ़िंग।",
    startConsultation: "परामर्श शुरू करें",
    quickActions: "त्वरित कार्य",
    askAI: "AI से पूछें",
    askAIDesc: "तुरंत कानूनी उत्तर पाएं",
    challanCalc: "चालान कैल्क",
    challanCalcDesc: "अपने जुर्माने का अनुमान लगाएं",
    lawLibrary: "कानून पुस्तकालय",
    lawLibraryDesc: "500+ नियम ब्राउज़ करें",
    lawsIndexed: "कानून अनुक्रमित",
    statesCovered: "राज्य कवर किए गए",
    aiAccuracy: "AI सटीकता",
    available: "उपलब्ध",
    featuredLaws: "प्रमुख कानून",
    viewAll: "सभी देखें",
    calcTitle: "चालान कैलकुलेटर",
    calcSubtitle: "राज्य नियमों और वाहन प्रकार के आधार पर सटीक यातायात जुर्माना गणना करें।",
    vehicleType: "वाहन प्रकार",
    twoWheeler: "दुपहिया",
    threeWheeler: "तिपहिया",
    fourWheeler: "चारपहिया",
    heavyVehicle: "भारी वाहन",
    violationType: "उल्लंघन प्रकार",
    stateRegion: "राज्य / क्षेत्र",
    repeatOffense: "दोहरा अपराध",
    repeatDesc: "दोहरे अपराधियों के लिए जुर्माना आमतौर पर दोगुना होता है",
    active: "सक्रिय",
    calculating: "गणना हो रही है...",
    calculateFine: "जुर्माना गणना करें",
    challanEstimate: "चालान अनुमान",
    violation: "उल्लंघन",
    legalSection: "कानूनी धारा",
    region: "क्षेत्र",
    legalExplanation: "कानूनी व्याख्या",
    estimateDisclaimer: "यह एक अनुमान है। वास्तविक जुर्माना भिन्न हो सकता है।",
    poweredBy: "Gemini AI और RAG आर्किटेक्चर द्वारा संचालित",
    heroTitle1: "भारतीय यातायात कानूनों के लिए",
    heroTitle2: "आपका AI साथी",
    heroSubtitle: "चालान, धाराओं, उल्लंघनों और राज्य-विशिष्ट यातायात नियमों पर तत्काल कानूनी स्पष्टता।",
    tryFree: "AI सहायक मुफ्त आज़माएं",
    challanCalculator: "चालान कैलकुलेटर",
    comprehensiveTools: "व्यापक कानूनी उपकरण",
    toolsSubtitle: "भारतीय यातायात नियमों को समझने के लिए सब कुछ।",
    aiLegalChat: "AI कानूनी चैट",
    aiLegalChatDesc: "जटिल यातायात कानून प्रश्न पूछें और Gemini AI द्वारा तत्काल उत्तर प्राप्त करें।",
    startConsult: "परामर्श शुरू करें",
    calcFine: "जुर्माना गणना करें",
    browseLibrary: "पुस्तकालय ब्राउज़ करें",
    lawLibraryTitle: "कानून पुस्तकालय",
    lawLibraryLandingDesc: "मोटर वाहन अधिनियम, राज्य-स्तरीय यातायात नियम और हालिया संशोधन ब्राउज़ करें।",
    stateIntelligence: "राज्य-विशिष्ट बुद्धिमत्ता",
    stateIntelligenceDesc: "हर भारतीय राज्य के लिए स्थानीयकृत यातायात कानून डेटा।",
    moreStates: "+20 और राज्य",
    ctaTitle: "अपने यातायात अधिकारों को समझने के लिए तैयार?",
    ctaSubtitle: "Pothprohori का उपयोग करने वाले हज़ारों नागरिकों से जुड़ें।",
    getStartedFree: "मुफ्त शुरू करें",
    footerDisclaimer: "शैक्षिक उद्देश्यों के लिए। सरकारी स्रोतों से सत्यापित करें।",
    signIn: "साइन इन",
    getStarted: "शुरू करें",
    aiAssistantNav: "AI सहायक",
    challanCalcNav: "चालान कैलकुलेटर",
    lawLibraryNav: "कानून पुस्तकालय",
  },
  bn: {
    appName: "আইনি AI সহায়ক",
    appSubtitle: "ভারতীয় যানবাহন আইন, জরিমানা বা নিয়ম সম্পর্কে যেকোনো প্রশ্ন করুন।",
    newChat: "নতুন চ্যাট",
    noPrevChats: "কোনো আগের চ্যাট নেই",
    greeting: "আমি কীভাবে সাহায্য করতে পারি?",
    greetingSubtitle: "আমি আপনার AI যানবাহন আইন বিশেষজ্ঞ। চালান, রাজ্য-নির্দিষ্ট নিয়ম বা জরিমানা সম্পর্কে জিজ্ঞাসা করুন।",
    placeholder: "Pothprohori AI-কে বার্তা পাঠান...",
    you: "আপনি",
    aiAssistant: "AI সহায়ক",
    references: "তথ্যসূত্র:",
    disclaimer: "AI ভুল করতে পারে। সরকারি সূত্র থেকে যাচাই করুন।",
    responseLanguage: "উত্তরের ভাষা",
    suggestions: ["হেলমেট ছাড়া গাড়ি চালালে জরিমানা কত?", "দিল্লিতে মাতাল অবস্থায় গাড়ি চালানোর নিয়ম কী?", "MV আইনের ধারা 177 বিস্তারিত বোঝান"],
    navHome: "হোম",
    navChat: "চ্যাট",
    navCalc: "ক্যালক",
    navLibrary: "লাইব্রেরি",
    signOut: "লগ আউট",
    welcomeBack: "স্বাগতম,",
    dailyBriefing: "আপনার দৈনিক যানবাহন আইন ব্রিফিং।",
    startConsultation: "পরামর্শ শুরু করুন",
    quickActions: "দ্রুত কার্যক্রম",
    askAI: "AI-কে জিজ্ঞাসা করুন",
    askAIDesc: "তাৎক্ষণিক আইনি উত্তর পান",
    challanCalc: "চালান ক্যালক",
    challanCalcDesc: "আপনার জরিমানা অনুমান করুন",
    lawLibrary: "আইন পাঠাগার",
    lawLibraryDesc: "৫০০+ নিয়ম ব্রাউজ করুন",
    lawsIndexed: "আইন তালিকাভুক্ত",
    statesCovered: "রাজ্য কভার",
    aiAccuracy: "AI নির্ভুলতা",
    available: "সর্বদা উপলব্ধ",
    featuredLaws: "প্রধান আইন",
    viewAll: "সব দেখুন",
    calcTitle: "চালান ক্যালকুলেটর",
    calcSubtitle: "রাজ্যের নিয়ম এবং যানবাহনের ধরন অনুযায়ী সঠিক জরিমানা গণনা করুন।",
    vehicleType: "যানবাহনের ধরন",
    twoWheeler: "দু-চাকার",
    threeWheeler: "তিন-চাকার",
    fourWheeler: "চার-চাকার",
    heavyVehicle: "ভারী যানবাহন",
    violationType: "লঙ্ঘনের ধরন",
    stateRegion: "রাজ্য / অঞ্চল",
    repeatOffense: "পুনরাবৃত্ত অপরাধ",
    repeatDesc: "পুনরাবৃত্ত অপরাধীদের জরিমানা সাধারণত দ্বিগুণ হয়",
    active: "সক্রিয়",
    calculating: "গণনা হচ্ছে...",
    calculateFine: "জরিমানা গণনা করুন",
    challanEstimate: "চালান অনুমান",
    violation: "লঙ্ঘন",
    legalSection: "আইনি ধারা",
    region: "অঞ্চল",
    legalExplanation: "আইনি ব্যাখ্যা",
    estimateDisclaimer: "এটি একটি অনুমান। প্রকৃত জরিমানা ভিন্ন হতে পারে।",
    poweredBy: "Gemini AI এবং RAG আর্কিটেকচার দ্বারা চালিত",
    heroTitle1: "ভারতীয় যানবাহন আইনের জন্য",
    heroTitle2: "আপনার AI সঙ্গী",
    heroSubtitle: "চালান, ধারা, লঙ্ঘন এবং রাজ্য-নির্দিষ্ট যানবাহন নিয়মের উপর তাৎক্ষণিক আইনি স্বচ্ছতা।",
    tryFree: "AI সহায়ক বিনামূল্যে ব্যবহার করুন",
    challanCalculator: "চালান ক্যালকুলেটর",
    comprehensiveTools: "সম্পূর্ণ আইনি সরঞ্জাম",
    toolsSubtitle: "ভারতীয় যানবাহন নিয়ম বোঝার জন্য সবকিছু।",
    aiLegalChat: "AI আইনি চ্যাট",
    aiLegalChatDesc: "জটিল যানবাহন আইন প্রশ্ন করুন এবং Gemini AI দ্বারা তাৎক্ষণিক উত্তর পান।",
    startConsult: "পরামর্শ শুরু করুন",
    calcFine: "জরিমানা গণনা করুন",
    browseLibrary: "পাঠাগার ব্রাউজ করুন",
    lawLibraryTitle: "আইন পাঠাগার",
    lawLibraryLandingDesc: "মোটর ভেহিকেলস অ্যাক্ট, রাজ্য-স্তরের নিয়ম এবং সাম্প্রতিক সংশোধনী ব্রাউজ করুন।",
    stateIntelligence: "রাজ্য-নির্দিষ্ট বুদ্ধিমত্তা",
    stateIntelligenceDesc: "প্রতিটি ভারতীয় রাজ্যের জন্য স্থানীয় যানবাহন আইন ডেটা।",
    moreStates: "+২০ আরও রাজ্য",
    ctaTitle: "আপনার যানবাহন অধিকার বুঝতে প্রস্তুত?",
    ctaSubtitle: "Pothprohori ব্যবহারকারী হাজার হাজার নাগরিকদের সাথে যোগ দিন।",
    getStartedFree: "বিনামূল্যে শুরু করুন",
    footerDisclaimer: "শিক্ষামূলক উদ্দেশ্যে। সরকারি সূত্র থেকে যাচাই করুন।",
    signIn: "সাইন ইন",
    getStarted: "শুরু করুন",
    aiAssistantNav: "AI সহায়ক",
    challanCalcNav: "চালান ক্যালকুলেটর",
    lawLibraryNav: "আইন পাঠাগার",
  },
  ta: {
    appName: "சட்ட AI உதவியாளர்",
    appSubtitle: "இந்திய போக்குவரத்து சட்டங்கள், அபராதம் பற்றி கேளுங்கள்.",
    newChat: "புதிய சாட்",
    noPrevChats: "முந்தைய சாட் இல்லை",
    greeting: "எப்படி உதவலாம்?",
    greetingSubtitle: "நான் உங்கள் AI போக்குவரத்து சட்ட நிபுணர். சல்லான், மாநில விதிமுறைகள் பற்றி கேளுங்கள்.",
    placeholder: "Pothprohori AI-க்கு செய்தி...",
    you: "நீங்கள்",
    aiAssistant: "AI உதவியாளர்",
    references: "மூலங்கள்:",
    disclaimer: "AI தவறுகள் செய்யலாம். அரசு மூலங்களில் சரிபார்க்கவும்.",
    responseLanguage: "பதில் மொழி",
    suggestions: ["ஹெல்மெட் இல்லாமல் ஓட்டினால் அபராதம் என்ன?", "டெல்லியில் குடிபோதையில் வாகனம் ஓட்டும் விதிமுறைகள் என்ன?", "MV சட்டம் பிரிவு 177 விளக்கவும்"],
    navHome: "முகப்பு",
    navChat: "சாட்",
    navCalc: "கணக்கி",
    navLibrary: "நூலகம்",
    signOut: "வெளியேறு",
    welcomeBack: "வரவேற்கிறோம்,",
    dailyBriefing: "உங்கள் தினசரி போக்குவரத்து சட்ட சுருக்கம்.",
    startConsultation: "ஆலோசனை தொடங்கு",
    quickActions: "விரைவு செயல்கள்",
    askAI: "AI-யிடம் கேளுங்கள்",
    askAIDesc: "உடனடி சட்ட பதில்கள்",
    challanCalc: "சல்லான் கணக்கி",
    challanCalcDesc: "அபராதத்தை மதிப்பிடுங்கள்",
    lawLibrary: "சட்ட நூலகம்",
    lawLibraryDesc: "500+ விதிகள் உலாவுங்கள்",
    lawsIndexed: "சட்டங்கள்",
    statesCovered: "மாநிலங்கள்",
    aiAccuracy: "AI துல்லியம்",
    available: "எப்போதும்",
    featuredLaws: "முக்கிய சட்டங்கள்",
    viewAll: "அனைத்தையும் காண்",
    calcTitle: "சல்லான் கணக்கி",
    calcSubtitle: "மாநில விதிகள் மற்றும் வாகன வகை அடிப்படையில் அபராதம் கணக்கிடுங்கள்.",
    vehicleType: "வாகன வகை",
    twoWheeler: "இரு சக்கர",
    threeWheeler: "முச்சக்கர",
    fourWheeler: "நான்கு சக்கர",
    heavyVehicle: "கனரக வாகனம்",
    violationType: "மீறல் வகை",
    stateRegion: "மாநிலம் / பகுதி",
    repeatOffense: "மீண்டும் குற்றம்",
    repeatDesc: "மீண்டும் குற்றவாளிகளுக்கு அபராதம் இரட்டிப்பாகும்",
    active: "செயலில்",
    calculating: "கணக்கிடுகிறது...",
    calculateFine: "அபராதம் கணக்கிடு",
    challanEstimate: "சல்லான் மதிப்பீடு",
    violation: "மீறல்",
    legalSection: "சட்டப் பிரிவு",
    region: "பகுதி",
    legalExplanation: "சட்ட விளக்கம்",
    estimateDisclaimer: "இது ஒரு மதிப்பீடு. உண்மையான அபராதம் மாறுபடலாம்.",
    poweredBy: "Gemini AI மற்றும் RAG மூலம்",
    heroTitle1: "இந்திய போக்குவரத்து சட்டங்களுக்கான",
    heroTitle2: "உங்கள் AI கூட்டாளி",
    heroSubtitle: "சல்லான், பிரிவுகள், மீறல்கள் பற்றிய உடனடி சட்ட தெளிவு.",
    tryFree: "AI உதவியாளர் இலவசம்",
    challanCalculator: "சல்லான் கணக்கி",
    comprehensiveTools: "முழுமையான சட்ட கருவிகள்",
    toolsSubtitle: "இந்திய போக்குவரத்து விதிகளை புரிந்துகொள்ள எல்லாம்.",
    aiLegalChat: "AI சட்ட சாட்",
    aiLegalChatDesc: "சிக்கலான போக்குவரத்து சட்ட கேள்விகளுக்கு Gemini AI மூலம் உடனடி பதில்கள்.",
    startConsult: "ஆலோசனை தொடங்கு",
    calcFine: "அபராதம் கணக்கிடு",
    browseLibrary: "நூலகம் உலாவு",
    lawLibraryTitle: "சட்ட நூலகம்",
    lawLibraryLandingDesc: "மோட்டார் வாகன சட்டம், மாநில விதிகள் மற்றும் திருத்தங்களை உலாவுங்கள்.",
    stateIntelligence: "மாநில-சிறப்பு நுண்ணறிவு",
    stateIntelligenceDesc: "ஒவ்வொரு இந்திய மாநிலத்திற்கும் போக்குவரத்து சட்ட தரவு.",
    moreStates: "+20 மாநிலங்கள்",
    ctaTitle: "உங்கள் போக்குவரத்து உரிமைகளை புரிந்துகொள்ள தயாரா?",
    ctaSubtitle: "Pothprohori பயன்படுத்தும் ஆயிரக்கணக்கான குடிமக்களுடன் இணையுங்கள்.",
    getStartedFree: "இலவசமாக தொடங்கு",
    footerDisclaimer: "கல்வி நோக்கங்களுக்காக. அரசு மூலங்களில் சரிபார்க்கவும்.",
    signIn: "உள்நுழை",
    getStarted: "தொடங்கு",
    aiAssistantNav: "AI உதவியாளர்",
    challanCalcNav: "சல்லான் கணக்கி",
    lawLibraryNav: "சட்ட நூலகம்",
  },
  te: {
    appName: "చట్ట AI సహాయకుడు",
    appSubtitle: "భారతీయ ట్రాఫిక్ చట్టాలు, జుర్మానాల గురించి ఏదైనా అడగండి.",
    newChat: "కొత్త చాట్",
    noPrevChats: "ముందు చాట్ లేవు",
    greeting: "నేను ఎలా సహాయం చేయగలను?",
    greetingSubtitle: "నేను మీ AI ట్రాఫిక్ చట్ట నిపుణుడను. చల్లాన్, రాష్ట్ర నిబంధనలు అడగండి.",
    placeholder: "Pothprohori AIకి సందేశం పంపండి...",
    you: "మీరు",
    aiAssistant: "AI సహాయకుడు",
    references: "సందర్భాలు:",
    disclaimer: "AI తప్పులు చేయవచ్చు. అధికారిక వనరులతో ధృవీకరించండి.",
    responseLanguage: "సమాధాన భాష",
    suggestions: ["హెల్మెట్ లేకుండా నడిస్తే జుర్మానా ఎంత?", "హైదరాబాద్లో మద్యంతో నడపడానికి నిబంధనలు ఏమిటి?", "MV చట్టం సెక్షన్ 177 వివరించండి"],
    navHome: "హోమ్",
    navChat: "చాట్",
    navCalc: "క్యాల్క్",
    navLibrary: "లైబ్రరీ",
    signOut: "లాగ్ అవుట్",
    welcomeBack: "స్వాగతం,",
    dailyBriefing: "మీ రోజువారీ ట్రాఫిక్ చట్ట బ్రీఫింగ్.",
    startConsultation: "సంప్రదింపు ప్రారంభించండి",
    quickActions: "త్వరిత చర్యలు",
    askAI: "AI ని అడగండి",
    askAIDesc: "తక్షణ చట్ట సమాధానాలు",
    challanCalc: "చల్లాన్ క్యాల్క్",
    challanCalcDesc: "మీ జుర్మానా అంచనా",
    lawLibrary: "చట్ట గ్రంథాలయం",
    lawLibraryDesc: "500+ నియమాలు బ్రౌజ్ చేయండి",
    lawsIndexed: "చట్టాలు",
    statesCovered: "రాష్ట్రాలు",
    aiAccuracy: "AI ఖచ్చితత్వం",
    available: "ఎల్లప్పుడూ",
    featuredLaws: "ప్రధాన చట్టాలు",
    viewAll: "అన్నీ చూడండి",
    calcTitle: "చల్లాన్ కాలిక్యులేటర్",
    calcSubtitle: "రాష్ట్ర నిబంధనలు మరియు వాహన రకం ప్రకారం జుర్మానా లెక్కించండి.",
    vehicleType: "వాహన రకం",
    twoWheeler: "ద్విచక్ర",
    threeWheeler: "త్రిచక్ర",
    fourWheeler: "నాలుగు చక్ర",
    heavyVehicle: "భారీ వాహనం",
    violationType: "ఉల్లంఘన రకం",
    stateRegion: "రాష్ట్రం / ప్రాంతం",
    repeatOffense: "పునరావృత నేరం",
    repeatDesc: "పునరావృత నేరస్తులకు జుర్మానా రెట్టింపు",
    active: "సక్రియం",
    calculating: "లెక్కిస్తోంది...",
    calculateFine: "జుర్మానా లెక్కించు",
    challanEstimate: "చల్లాన్ అంచనా",
    violation: "ఉల్లంఘన",
    legalSection: "చట్ట సెక్షన్",
    region: "ప్రాంతం",
    legalExplanation: "చట్ట వివరణ",
    estimateDisclaimer: "ఇది అంచనా. అసలు జుర్మానా భిన్నంగా ఉండవచ్చు.",
    poweredBy: "Gemini AI మరియు RAG ద్వారా",
    heroTitle1: "భారతీయ ట్రాఫిక్ చట్టాలకు",
    heroTitle2: "మీ AI భాగస్వామి",
    heroSubtitle: "చల్లాన్, సెక్షన్లు, ఉల్లంఘనలపై తక్షణ చట్ట స్పష్టత.",
    tryFree: "AI సహాయకుడు ఉచితం",
    challanCalculator: "చల్లాన్ కాలిక్యులేటర్",
    comprehensiveTools: "సమగ్ర చట్ట సాధనాలు",
    toolsSubtitle: "భారతీయ ట్రాఫిక్ నిబంధనలను అర్థం చేసుకోవడానికి.",
    aiLegalChat: "AI చట్ట చాట్",
    aiLegalChatDesc: "సంక్లిష్ట ట్రాఫిక్ చట్ట ప్రశ్నలకు Gemini AI ద్వారా తక్షణ సమాధానాలు.",
    startConsult: "సంప్రదింపు ప్రారంభించు",
    calcFine: "జుర్మానా లెక్కించు",
    browseLibrary: "గ్రంథాలయం బ్రౌజ్ చేయి",
    lawLibraryTitle: "చట్ట గ్రంథాలయం",
    lawLibraryLandingDesc: "మోటార్ వెహికల్ యాక్ట్, రాష్ట్ర నిబంధనలు మరియు సవరణలు బ్రౌజ్ చేయండి.",
    stateIntelligence: "రాష్ట్ర-నిర్దిష్ట మేధస్సు",
    stateIntelligenceDesc: "ప్రతి భారతీయ రాష్ట్రానికి ట్రాఫిక్ చట్ట డేటా.",
    moreStates: "+20 రాష్ట్రాలు",
    ctaTitle: "మీ ట్రాఫిక్ హక్కులను అర్థం చేసుకోవడానికి సిద్ధమా?",
    ctaSubtitle: "Pothprohori వాడుతున్న వేలాది పౌరులతో చేరండి.",
    getStartedFree: "ఉచితంగా ప్రారంభించు",
    footerDisclaimer: "విద్యా ప్రయోజనాల కోసం. అధికారిక వనరులతో ధృవీకరించండి.",
    signIn: "సైన్ ఇన్",
    getStarted: "ప్రారంభించు",
    aiAssistantNav: "AI సహాయకుడు",
    challanCalcNav: "చల్లాన్ కాలిక్యులేటర్",
    lawLibraryNav: "చట్ట గ్రంథాలయం",
  },
};

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  currentLang: typeof LANGUAGES[0];
  t: Record<string, any>;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  currentLang: LANGUAGES[0],
  t: UI_TEXT.en,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState(
    () => localStorage.getItem("pothprohori_lang") || "en"
  );
  const setLanguage = (lang: string) => {
    localStorage.setItem("pothprohori_lang", lang);
    setLanguageState(lang);
  };
  const currentLang = LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];
  const t = UI_TEXT[language] || UI_TEXT.en;
  return (
    <LanguageContext.Provider value={{ language, setLanguage, currentLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
